### ISSUE TITLE
Crash v0.9.11

### ISSUE THREAD

**Issue by JPe2** [PatrickSannes/BetterLogic#11]
crash V0.9.11 direct after update:  also  a restart gives directly the error:
Stack trace:

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/app.js:3:23)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

Exit code: 1
Exit signal: null

**Comment by jjtbsomhorst** [comment]
Same here.

**Comment by daneedk** [comment]
Same here :(

**Comment by ghost** [comment]
same here

**Comment by chrisboer** [comment]
Same here

**Comment by 2benl** [comment]
Same here

**Comment by PatrickSannes** [comment]
It's fixed in 0.9.12

**Comment by gldrenthe89** [comment]
How do i get v0.9.12?

**Comment by chrisboer** [comment]
Already installed Patrick Thanks ;-)

**Comment by ghost** [comment]
How did you?

**Comment by chrisboer** [comment]
@gldrenthe89 developer install look on athom forum and check how to do this
