### ISSUE TITLE
Better logic crash

### ISSUE THREAD

**Issue by posthok** [PatrickSannes/BetterLogic#9]
Used Bitflip for the first time.
app crashes with the following message:
Stack trace:

TypeError: variable.value.toLowerCase is not a function
at Object.<anonymous> (/lib/flow/conditions.js:10:44)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:12:37
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 1
Exit signal: null

**Comment by PatrickSannes** [comment]
Is the boolean value still there that was used for the bitflip? Can you
export your variables? What variable name was used for the bitflip?

**Comment by posthok** [comment]
I'm checking my flown now. I used bitflips instead of strings.
Checking my flows the old string names i deleted are still in my flow because i gave the bitflips the same name.

**Comment by PatrickSannes** [comment]
That could case the problem. You really have to reselect them to get it to
work.

Hope it works.

**Comment by jeroenvano** [comment]
Since update v0.9.11 - 21.06.17 - APP CRASH. 

Worked fine until Homey auto updated the app. 
This is the stack trace:

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
